name: Run Selenium Tests Daily

on:
  schedule:
    # Runs at 2:00 AM PST (10:00 UTC)
    - cron: '0 10 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install dependencies
    - name: Install dependencies
      run: mvn install

    # Run TestNG tests
    - name: Run Selenium Tests
      run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml

    # Archive test results
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/
